### ISSUE TITLE
Problem using vro-plugin-user with sudo. Cannot display environment/role list.

### ISSUE THREAD

**Issue by fduranti** [puppetlabs/puppet-vro-starter_content#29]
I'm not sure if it's a problem of my puppet enterprise installation or it's general but the /etc/puppetlabs/code directory in my installation have those permissions:
`drwxr-x---    3 pe-puppet                 pe-puppet                  4096 Jun  5 10:08 code
`
vro/vra plugin is trying to do a ls /etc/puppetlabs/code/environment and it fail with this error on the orchestrator:
```
2017-06-05 14:20:34.075+0200 [http-nio-127.0.0.1-8280-exec-8] ERROR {} [BaseController] Error invoking REST [unknown]
ch.dunes.util.DunesServerException: Action 'getEnvironments' in module 'com.puppet.o11n.plugin.puppet' failed : Failed to get list of environments from master. exitCode=2 error=ls: cannot access /etc/puppetlabs/code/environments/: Permission denied
 (unnamed script#31)
	at com.vmware.o11n.service.impl.ScriptModuleRuntimeServiceImpl.executeServerAction(ScriptModuleRuntimeServiceImpl.java:58)
	at com.vmware.o11n.service.impl.ScriptModuleRuntimeServiceImpl.executeServerActionPriviliged(ScriptModuleRuntimeServiceImpl.java:94)
	at sun.reflect.GeneratedMethodAccessor722.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy315.executeServerActionPriviliged(Unknown Source)
	at com.vmware.o11n.service.factory.VcoFactoryFacade.executeServerActionPriviliged(VcoFactoryFacade.java:2491)
	at sun.reflect.GeneratedMethodAccessor714.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vmware.o11n.service.security.AccessRightsInterceptor.invoke(AccessRightsInterceptor.java:98)
	at com.vmware.o11n.service.security.AccessRightsInterceptor.invoke(AccessRightsInterceptor.java:89)
	at com.vmware.o11n.service.factory.LocalVSOFactoryInvocationHandler.invokeOperation(LocalVSOFactoryInvocationHandler.java:199)
	at com.vmware.o11n.service.factory.LocalVSOFactoryInvocationHandler.doInvoke(LocalVSOFactoryInvocationHandler.java:255)
	at com.vmware.o11n.service.factory.LocalVSOFactoryInvocationHandler.invoke(LocalVSOFactoryInvocationHandler.java:128)
	at com.sun.proxy.$Proxy361.executeServerActionPriviliged(Unknown Source)
	at ch.dunes.model.client.VSOFactoryClient.executeServerActionPriviliged(VSOFactoryClient.java:2829)
	at com.vmware.o11n.web.action.ActionController.doExecuteAction(ActionController.java:478)
	at com.vmware.o11n.web.action.ActionController.executeActionByName(ActionController.java:404)
	at sun.reflect.GeneratedMethodAccessor713.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.vmware.o11n.web.Slf4jRequestLoggingFilter.doFilterInternal(Slf4jRequestLoggingFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.vmware.o11n.web.SlashAppendingFilter.doFilterInternal(SlashAppendingFilter.java:25)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.vmware.o11n.json.DefaultJsonVersionHeaderFilter.doFilter(DefaultJsonVersionHeaderFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.vmware.o11n.web.cluster.RestActiveNodeFilter.doFilter(RestActiveNodeFilter.java:63)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.vmware.o11n.web.auth.http.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:97)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

The user is created by default without any group (so it get only a default group equal to username). 
I've added the vro-plugin-user to pe-puppet group and it works (or it should run the various ls command with sudo too and sudo needs to be configured).

**Comment by hokutolabs** [comment]
We had the same issue when I was assigned to a Jumpstart project, plus turning on audit logs on the Master we noticed that sometimes the plugin user was not using/could not use sudo at all despite the checkbox being set "VMware side".

**Comment by turbodog** [comment]
Is the vro-plugin-user in sudoers? See the code in https://github.com/puppetlabs/puppet-vro-starter_content/blob/production/modules/vro_plugin_user/manifests/init.pp shows that will create the system user, enable it for sudo as well as create a PE user and its security role. This class should have been applied to your master server via the `vra_nc_setup.sh` script

**Comment by fduranti** [comment]
I've used that module to create the user. My user was created correctly and it has all the sudo command from the module:

```
/etc/passwd:
vro-plugin-user:x:1003:1004::/home/vro-plugin-user:/bin/bash

/etc/group:
vro-plugin-user:x:1004:

sudo -l :
Matching Defaults entries for vro-plugin-user on this host:
    !visiblepw, always_set_home, env_reset, env_keep="COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS", env_keep+="MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE",
    env_keep+="LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES", env_keep+="LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE", env_keep+="LC_TIME LC_ALL
    LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY", secure_path=/sbin\:/bin\:/usr/sbin\:/usr/bin, !requiretty

Runas and Command-specific defaults for vro-plugin-user:
    Defaults!/opt/puppetlabs/bin/puppet preview *, /usr/bin/cat /etc/puppetlabs/code/environments/*/.r10k-deploy.json, /opt/puppetlabs/bin/puppet-query * !requiretty

User vro-plugin-user may run the following commands on this host:
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet node purge *
    (root) NOPASSWD: !/opt/puppetlabs/bin/puppet node purge *[[\:blank\:]]*
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet config print *
    (root) NOPASSWD: !/opt/puppetlabs/bin/puppet config print *[[\:blank\:]]*
    (root) NOPASSWD: /opt/puppetlabs/bin/facter -p puppetversion
    (root) NOPASSWD: /opt/puppetlabs/bin/facter -p pe_server_version
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet agent -t
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet agent --test --color\=false --detailed-exitcodes
    (root) NOPASSWD: /bin/kill -HUP *
    (root) NOPASSWD: !/bin/kill -HUP *[[\:blank\:]]*
    (root) NOPASSWD: !/opt/puppetlabs/bin/puppet node purge itrompm10.q8int.com
    (root) NOPASSWD: !/opt/puppetlabs/bin/puppet node purge pe-internal-mcollective-servers
    (root) NOPASSWD: !/opt/puppetlabs/bin/puppet node purge pe-internal-peadmin-mcollective-client
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet resource service puppet ensure\=stopped
    (root) NOPASSWD: /opt/puppetlabs/bin/puppet resource service puppet ensure\=running enable\=true
    (root) NOPASSWD: /bin/cp /etc/puppetlabs/puppet/ssl/ca/ca_crl.pem /etc/puppetlabs/puppet/ssl/crl.pem
```

There's no ls /etc/puppetlabs/code* command in the sudo commands configured by the plugin and even if it was there the vro-plugin run the ls command without sudo so it will not work.
What don't work is that when you go choose for environment or role in the web interface of VRA nothing is shown as there's a permission error because the /etc/puppetlabs/code directory is 0770 and owned:group by pe-puppet:pe-puppet so the module created user cannot access it to do a ls /etc/puppetlabs/code/environment to see the list of environment.

Using the vro-plugin with root work correctly.  To make it work correctly without root permission there are 2 possibility:
1- Change the vro-plugin so that it will do a "sudo ls" instead of only "ls" (and add ls as sudo command in this module).
2- The module can create the user with primary or secondary group pe-puppet so that the user can access the file in /etc/puppetlabs/code

Adding pe-puppet group to the pe-puppet user work correctly.

I'm not sure if the problem is related only to my installation but it seems correct that the /etc/puppetlabs/code directory is only accessible to pe-puppet:pe-puppet user:group.

**Comment by jpadams** [comment]
@fduranti We it seems that your umask may be too restrictive on your master. We'll add a note in short term that we require a umask that keeps the "other" readable. For example 0022 yielding files with 0644 and directories with 0755 permission by default. I'm guessing your umask is something like 0027 and is thus creating a directory with 0770 which the "other" user of vro-plugin-user cannot access.

Thanks to @boozezela for suggesting this.

Longer term, we may simply add `sudo` support to our `ls` command.

**Comment by fduranti** [comment]
@jpadams My umask is correct and is 0022. The standard Puppet installation /etc/puppetlabs/code directory have 0750 permission and pe-puppet:pe-puppet user group permission.
I've just changed it to 0755 and when I run puppet agent (so at next run of puppet) it will be reset to 0750 as you can see with this run. 

```
[root@puppet puppetlabs]# umask
0022
[root@puppet puppetlabs]# chmod o+rx code
[root@puppet puppetlabs]# puppet agent -t --no-noop
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for itrompm10.q8int.com
Info: Applying configuration version '4362b42 - PE File Sync Service, Thu Jun 15 16:57:32 2017 +0200 : code-manager deploy signature: '895f4e96f466e69b6f561c1facf1467475554d45''
Notice: /Stage[main]/Puppet_enterprise::Master::File_sync/File[/etc/puppetlabs/code]/mode: mode changed '0755' to '0750'
Notice: Applied catalog in 11.26 seconds
[root@puppet puppetlabs]# 
```

The only solution I can see are to change the vro-plugin-user to have a secondary pe-puppet group or change the plugin itself so that it run also the "ls /etc/puppetlabs/code/environment" (and also all the other commands like ls /etc/puppetlabs/code/environement/envname/site/roles" (if it run this command to get the role list as I think) using sudo.

**Comment by ploeghvander** [comment]
Is this issue solved? I do get to choose the puppet environment in the VRA blueprint. Only I don't see any roles to choose from. Can anyone make a suggestion?

**Comment by jpadams** [comment]
After researching this with code manager turned on, we've found that the permissions of the /etc/puppetlabs/code directory do not allow the vro-plugin-user (service account meant to allow interaction between the vRO plugin code and the PE Master server) to read the files. A fix is to ensure that the vro-plugin-user is in the pe-puppet group and thus able to read the code files where roles are defined. That was implemented in the starter content here: https://github.com/puppetlabs/puppet-vro-starter_content/commit/7447f04f039b3f4a522dcec3842bb31f9f8ed46d#diff-fdc04c7363c90df557b48da461b8d9ad

@ploeghvander FYI
